### ISSUE TITLE
Pool queue length is not calculated correctly and always returns 0

### ISSUE THREAD

**Issue by moredatapls** [webdevops/azure-devops-exporter#66]
In https://github.com/webdevops/azure-devops-exporter/blob/8b8b1a2cd592097b47b26786602e3d180a38216d/metrics_agentpool.go#L241C4-L241C4, the `agentPoolQueueLength` is calculated by checking for the presence of an `assignTime` field in the result of the `jobrequests` query.

This always yields a queue length of 0 for us. I believe that the way it is calculated is incorrect.

![image](https://github.com/webdevops/azure-devops-exporter/assets/11437312/ee118ffc-0681-4096-896d-667c4305d94b)

The screenshot above shows the result of the `jobrequests` query for us, and as you can see, the `assignTime` is always present, even for jobs that have not yet been executed (the one with ID 5).

We could check for the presence of the `result` field, although that would also count jobs that are currently running, I believe (which would be fine for me).

**Comment by mblaschke** [comment]
`azure_devops_agentpool_queue_length` should have the value of jobs which are still in queue but not yet assigned to any agent (and so not be executed).

Do you have waiting jobs or are most of the jobs executed immediately because you have enough agents?
The result is available once the job execution is done.

**Comment by moredatapls** [comment]
@mblaschke you are absolutely right, the queue length is correct, it was a mistake on my part.
